#!/bin/bash
#
#  RECPASS -- records one contiguous time slice to disk
#
#    ./recpass scanName recordTimeInSecs
# 
#----------------------------------------------------------
#  Defaults if not specified from command line: 
#     recording time is 220s / 3min40s
#----------------------------------------------------------
#  !! Edit these before use: !! 
#     - dir (RAID mount point)
#     - ./wr vsib mode
#     - frames per block multiplier in TOTALBLKS to match 
#       vsib mode and data rate
#----------------------------------------------------------

if [ "$1" == "" ]; then
  echo " ./recpass scanname [seconds] "
  exit
fi

# Where to place recorded files:
##dir=/raid/pass-${HEADSTK}-`date '+%y%j%H%M%S'`
##filenm="%06d"
dir=/raid/t
filenm=$1

mkdir -p $dir

# Default to 220 seconds, 3min40s.
if [ "$2" == "" ]; then
  SECS=220
  echo "defaulting to 220sec"
else
  SECS=$2
fi

# 800 frames/blocks/s at 512Mbit/s.
# 400 frames/blocks/s at 256Mbit/s.
# 200 frames/blocks/s at 128Mbit/s.
# One frame/block at 32 tracks is 90000 bytes with parity, 80000 without.
TOTALBLKS=$(( $SECS * 200 ))

# wr: blocksize totalblocks mode skip embed giga ndirs { path%d blks }
# --
# mode 0 for 32-bit; skip 0 samples, do not embed 1pps, no gigabit mode
# split into smaller files (at 512Mbit/s: 8000 blks ~360MB == 10sec)
# ./wr 80000 $TOTALBLKS 0 0 0 0 1 $dir/%06d 8000 < /dev/vsib
# or just one big file:
echo "./wr 80000 ${TOTALBLKS} 0 0 0 0 1 ${dir}/${filenm}.evn ${TOTALBLKS} < /dev/vsib"
./wr 80000 $TOTALBLKS 0 0 0 0 1 $dir/$filenm.evn $TOTALBLKS < /dev/vsib

